### PR TITLE
Amd

### PR DESCRIPTION
**Pull request by jacac**
Hello Gordon,

this is a rewrite to use AMD loading see (https://docs.moodle.org/dev/Javascript_Modules).
I've update the required Moodle version because jQuery AMD was added in Moodle 2.9 (https://docs.moodle.org/dev/jQuery)
The styles were update to work on a Surface Pro which needed the default touch event disabled. I've tested this in Firefox, Chrome, on an iPad and Surface Pro.

### CODE REVIEW

**Comment by gbateson** [comment]
JACAC - thank you so much for all your work. The code looks great. 
I would like to keep the plugin flexible enough to run on ALL versions of Moodle >=2.0. Is there a way that we can detect for AMD and only use that if it is available. Otherwise, use the old code?

**Comment by jacac** [comment]
A different branch could be created to support version before 2.9. I've seen some go with Moodle default branching like MOODLE_28_STABLE would hold the everything before that.

**Comment by gbateson** [comment]
Dear Jacob,
thank you again for your work to add AMD files to the qtype_ordering plugin.

I have transferred your changes to the master branch and tested that the files work well in Moodle 2.9 - 3.4. I have left the old code in there so that plugin continues to work in Moodle 2.x. Perhaps when we get to Moodle 4.x I will remove all the debris from earlier Moodle versions :-) 

When you have time, please check the most recent changes I made to the plugin and confirm that it incorporates all the improvements that you made. After we've confirmed everything works, we can close this pull request.

Best regards
Gordon

**Comment by jacac** [comment]
Thanks Gordon,

master branch works with Moodle 3.4 and AMD modules are loaded. If you want I could clean up some global variables which are note used.

**Pull request closed without merging**
