### PR TITLE
Qtype_ordering: Numbering for lists (123.., abc...)

### PR DESCRIPTION
**Pull request by mkassaei**
Hi Gordon,
We had a requirement for some ordering questions to have some sort of numbering such as abc, 123, etc.
This patch implements this which is something similar to the multiple choice qtype. There are lost of minor changes, however, the default remain with no numbering.

Many thanks,
Mahmoud

### CODE REVIEW

**Comment by gbateson** [comment]
Mahmoud,
I found that on the settings page for Ordering questions, the default numbering for old questions from before the change, and also new questions after the change is "a. b. c.". This will be unexpected for people who upgrade. 

Therefore, if you have a chance, please force the default for this setting to "No numbering".
Otherwise, I will take a look this weekend.

**Comment by gbateson** [comment]
Mahmoud,
I have started working on the default values, so please leave it with me for a couple of days.

**Comment by mkassaei** [comment]
Hi Gordon,
Thanks for your prompt answer. I thinks I have forgotten to incorporate the new ‘answernumbering’ field into the following functions:

  *   export_to_xml()
  *   import_from_xml()
  *   export_to_gift()
  *   import_from_gift()

Do you want me to update these functions?

Many thanks,

[cid:image004.jpg@01D4A384.D90AC800]
[cid:image002.png@01D354B6.67899FD0]
Mahmoud Kassaei | Developer
IT Delivery, Information Technology
The Open University, Level 2 North, Berrill Building, Walton Hall, Milton Keynes, MK7 6AA
Tel: +44 (0) 1908 655458
[cid:image003.png@01D354B6.67899FD0]

**Comment by gbateson** [comment]
Mahmoud,
thanks for the heads up about the import/export functions. 
I have modified them to handle the new numbering field.

Please note the most recent version of this plugin includes the following modifications:
(1) I renamed the field from "answernumbering" to "numberingstyle", because the former sounds like a boolean question to me, whereas the latter lets give a range of values.
(2) I renamed two numbering options "ABCD" to "ABC" and "IIII" to "III", because I couldn't see the reason for having those two options be 4 chars in length.

Thanks for all your hard work on this plugin.

**Pull request merged**
