### PR TITLE
Ordering question type. Upgrade to work with Moodle 4.0, 4.1 and 4.2

### PR DESCRIPTION
**Pull request by timhunt**
Hi @gbateson 

These are the change to the Order question type required to make it work on Moodle 4.0 (which we have been running on our live server since December 2022). We are about to upgrade to Moodle 4.1, and these changes work there, and I have also tests with Moodle 4.2, and that seems to work too.

The pull request also include the three improvements the OU developed:
* pull #56
* pull #65 
* pull #67

Again, we have been running these changes on our main system since last December.

Let me know if you have any questions, but hopefully this lets you get a 4.x-compabtible version of ordering into the plugins database.

### CODE REVIEW

**Comment by timhunt** [comment]
Not, CI build for this version is all passing: https://github.com/timhunt/moodle-qtype_ordering/actions/runs/4829313458

**Comment by gbateson** [comment]
Thank you so much Tim, for making implementing these modifications and making them publicly available. I have merged them into the master branch on github and will publish them to the plugin repository on Moodle.org soon.

**Comment by golenkovm** [comment]
Hi @gbateson ,

It looks like Moodle 2.9-3.10 support has been dropped after this PR. Ideally a `MOODLE_29_STABLE` needed to be created before this PR had landed.
We have a Moodle 3.9 site that needs this plugin to be added but the recent code in master branch won't work due to [`$plugin->requires  = 2021051700; // Moodle 3.11.`](https://github.com/gbateson/moodle-qtype_ordering/blob/master/version.php#L31)
Would you be able to create it?
Much appreciated.

Kind regards,
Misha

**Comment by timhunt** [comment]
I would be surprised if just changing $plugin->requires  = 2021051700; fixes it. Did you try it?

The reason we marked this version of the plugin code as only compativle with Moodle 3.11 and later is becuase other changes in the code won't work with older Moodle versions. Since you are happy running a very old version of Moodle, why not continue to run the version of this plugin you are currently using?

**Comment by golenkovm** [comment]
Hi @timhunt 

I'm afraid you're missing my point. You must be very busy, but it's ok. Changing `$plugin->requires` is not what I suggested. Since this PR has been merged it's no longer possible to use the plugin with Moodles 2.9-3.10 (unless you point to a specific commit in master branch which is not nice). Thus, a branch (eg `MOODLE_29_STABLE` or `MOODLE_29-310_STABLE`) with the plugin code on the commit before this PR would need to be created so older Moodles could be pointed to this branch.

I mean this is great that this PR landed. I appreciate your work. It's just a matter of having stable plugin branches for older Moodle versions when master branch gets new features (that are not compatible with older Moodle versions).

PS: I wouldn't say that 3.9 is _very old_, it's still under security support. Also we can't continue using the version of this plugin that we are currently using because we're not using it yet. The plugin is about to be installed. I hope it clarifies.

Kind regards,
Misha

**Pull request merged**
