### PR TITLE
Preparing for core

### PR DESCRIPTION
**Pull request by vadimonus**
Hello. I have fixed phpcocs and coding style issues. You may take a look

### CODE REVIEW

**Comment by gbateson** [comment]
Thanks very much for all your hard work Vadim.
I have merged your PULL request.
How can we include your name somewhere in the code credits?

**Comment by gbateson** [comment]
The new release is now available on Moodle.org:
https://moodle.org/plugins/view.php?plugin=qtype_ordering

**Comment by vadimonus** [comment]
Just put it name into readme. In moodle traditionally copyright is marked to the person, who created file, so my name should be only in settings.php

**Comment by gbateson** [comment]
Understood. I have added a short "Development history" to the readme.txt, crediting you with the code improvements required for merging into Moodle core.

**Pull request merged**
